# Generated by Django 2.2.24 on 2021-09-19 05:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
