# Generated by Django 2.2.24 on 2021-09-26 15:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('featureimg', models.ImageField(blank=True, upload_to='giveaway/')),
                ('reward', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('winners', models.IntegerField(default=0)),
                ('sel_winners', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiveawayParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytm', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=50)),
                ('givid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Giveaway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
