# Generated by Django 2.2.24 on 2021-09-24 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=100)),
                ('mail', models.CharField(default='support@grabbersadda.in', max_length=100)),
                ('siteicon', models.ImageField(default='site_images/siteicon.png', upload_to='site_images/')),
                ('logo', models.ImageField(default='site_images/logo.png', upload_to='site_images/')),
                ('featureimg', models.ImageField(default='site_images/feature.jpg', upload_to='site_images/')),
                ('verify', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Useractivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimg', models.ImageField(default='profile_images/user.png', upload_to='profile_images/')),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('insta', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('membership', models.CharField(default='Basic', max_length=100)),
                ('role', models.CharField(default='Subscriber', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
