# Generated by Django 2.2.24 on 2021-09-14 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('bio', models.TextField()),
                ('facebook', models.CharField(max_length=100)),
                ('insta', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('membership', models.CharField(default='Basic', max_length=100)),
                ('role', models.CharField(default='Subscriber', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
