# Generated by Django 2.2.24 on 2021-09-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='refer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='refercode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
