# Generated by Django 2.2.24 on 2021-09-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210915_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='profile_images/user.png', upload_to='profile_images/'),
        ),
    ]
