# Generated by Django 2.2.24 on 2021-09-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useractivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='webinfo',
            name='logo',
            field=models.ImageField(default='site_images/logo.png', upload_to='site_images/'),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='siteicon',
            field=models.ImageField(default='site_images/siteicon.png', upload_to='site_images/'),
        ),
    ]
