# Generated by Django 2.2.24 on 2021-09-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210918_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='mail',
            field=models.CharField(default='support@grabbersadda.in', max_length=100),
        ),
    ]
