# Generated by Django 2.2.24 on 2021-09-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210919_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='verify',
            field=models.TextField(blank=True),
        ),
    ]
