# Generated by Django 2.2.24 on 2021-09-24 18:28

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('afflink', models.CharField(max_length=100)),
                ('storeimg', models.ImageField(null=True, upload_to='store_images/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='/', max_length=100)),
                ('thumbnail', models.ImageField(default='product_images/default.jpg', upload_to='product_images/')),
                ('description', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('sale_price', models.IntegerField(default=0)),
                ('original_price', models.IntegerField(default=0)),
                ('offers', models.TextField(blank=True)),
                ('affiliate_link', models.CharField(default=' ', max_length=150)),
                ('coupon', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, max_length=150)),
                ('price_compare', models.BooleanField(default=0)),
                ('pinned', models.BooleanField(default=0)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.Category')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.Store')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('bcomm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Comments')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
