# Generated by Django 2.2.24 on 2021-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='expiry',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
