# Generated by Django 2.2.24 on 2021-09-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210914_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='featureimg',
            field=models.CharField(default='', max_length=200),
        ),
    ]
