# Generated by Django 2.2.24 on 2021-09-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210925_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='expiry',
        ),
    ]
