# Generated by Django 2.2.24 on 2021-09-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210914_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('afflink', models.CharField(max_length=100)),
                ('featureimg', models.CharField(max_length=100)),
            ],
        ),
    ]
