# Generated by Django 2.2.24 on 2021-09-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
