# Generated by Django 2.2.24 on 2021-09-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(blank='True', upload_to='product_images/'),
        ),
    ]
