# Generated by Django 2.2.24 on 2021-09-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='coupon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
