# Generated by Django 2.2.24 on 2021-09-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offers',
            field=models.TextField(blank=True),
        ),
    ]
