# Generated by Django 2.2.24 on 2021-09-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210916_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='featureimg',
        ),
    ]
