# Generated by Django 2.2.24 on 2021-09-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_products_featureimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='featureimg',
        ),
        migrations.AddField(
            model_name='store',
            name='storeimg',
            field=models.ImageField(null=True, upload_to='store_images/'),
        ),
    ]
