# Generated by Django 2.2.24 on 2021-09-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210919_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
