# Generated by Django 2.2.24 on 2021-09-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='bcomm',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Comments'),
        ),
    ]
