# Generated by Django 2.2.24 on 2021-09-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210919_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='bcomm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Comments'),
        ),
    ]
