# Generated by Django 2.2.24 on 2021-09-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_store_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.CharField(default=models.CharField(max_length=100), max_length=150),
        ),
    ]
