# Generated by Django 2.2.24 on 2021-09-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_products_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tags',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
