# Generated by Django 2.2.24 on 2021-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20210924_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='expiry',
            field=models.DateField(blank=True),
        ),
    ]
