# Generated by Django 2.2.24 on 2021-09-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210924_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='expiry',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
