# Generated by Django 2.2.24 on 2021-09-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20210924_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='expiry',
        ),
    ]
